--daemonize=false
--pid_file=/home/sch/nebula/nebula-release-3.6/task-breakpad/runtime/nebula-graphd.pid
--local_config=true
--log_dir=/home/sch/nebula/nebula-release-3.6/task-breakpad/runtime/graphd-logs
--minloglevel=0
--v=0
--logbufsecs=0
--redirect_stdout=false
--stderrthreshold=0
--meta_server_addrs=127.0.0.1:45599
--local_ip=127.0.0.1
--port=29669
--ws_ip=127.0.0.1
--ws_http_port=29670
--ws_meta_http_port=29559
--num_netio_threads=1
--num_worker_threads=1
--enable_authorize=false
